### PR TITLE
Few minor Travis fixes lol

### PR DESCRIPTION
**Pull request by DeathlyPlays**

### CODE REVIEW

**Comment by Spandamn** [comment]
its too minor to be merged...

**Comment by DeathlyPlays** [comment]
tbh @Spandamn this server will go through a huge pain travis building like how Exiled did haha

**Comment by Spandamn** [comment]
Yeah... I plan on fixing it

**Comment by Spandamn** [comment]
Some day ™

**Comment by DeathlyPlays** [comment]
It took me two weeks for Exiled...

**Pull request closed without merging**
