### PR TITLE
Update moves.js

### PR DESCRIPTION
**Pull request by Ludicrousity**
Experiencing massive lag on my games so I'm closing chrome

### CODE REVIEW

**Comment by charizard8888** [comment]
Merge or no?

**Comment by charizard8888** [comment]
@Ludicrousity kek

**Comment by Spandamn** [comment]
@Ludicrousity

**Comment by charizard8888** [comment]
@Spandamn why is this happening 
updating...
From https://github.com/XpRienzo/DragonHeaven
* branch master -> FETCH_HEAD
34fe9c7..ace8f8d master -> origin/master
error: Your local changes to the following files would be overwritten by merge:
chat.js
Please, commit your changes or stash them before you can merge.
Aborting

help

**Comment by charizard8888** [comment]
@Ludicrousity merge?

**Comment by charizard8888** [comment]
Manually merged it the other way to avoid conflicts since I had made some changes in that file,

**Pull request closed without merging**
