### PR TITLE
Try this on some other file! idk if it works properly

### PR DESCRIPTION
**Pull request by KewlStatics**

### CODE REVIEW

**Comment by KewlStatics** [comment]
This feature works on my boilerplate idk about u

**Comment by KewlStatics** [comment]
If it work;s i will change colors for it later

**Comment by Spandamn** [comment]
What is this for

**Comment by KewlStatics** [comment]
A New Shop Design

**Comment by KewlStatics** [comment]
Better than old one

**Comment by Spandamn** [comment]
@charizard8888 please look at it

**Comment by KewlStatics** [comment]
it is a fixed file! The only thing is idk whether it works with Extra Updated Boilerplate

**Pull request merged**
