### PR TITLE
leagues.js

### PR DESCRIPTION
**Pull request by HiTechFlufi**
A league system. Provides a fun activity and reason to come on DragonHeaven often. Create leagues, recruit players, reach the top of the leaderboard, go into wars with other leagues, etc. Seeing from several other servers, it's a really popular activity that I'm sure would attract more players to DH.

### CODE REVIEW

**Comment by Spandamn** [comment]
I dont know whether this is required. Thoughts staff?
@charizard8888 @XpRienzo @Snaquaza @charizard8888 @ClassyZ

**Comment by Spandamn** [comment]
@EchoGaia

**Comment by EchoGaia** [comment]
I think Leagues are fun, when you look at other servers, like Azure being the most active right now, they have leagues. Are Leagues fun= Yes. Are leagues needed to have fun?= No.

That's my opinion on this stuff.

**Comment by charizard8888** [comment]
I'm not sure about this but won't say no 
Thoughts more staff? Xp Snaquaza EchoGaia?

**Comment by charizard8888** [comment]
More of tilted towards adding and testing it

**Comment by EchoGaia** [comment]
I already told my opinion @charizard8888

**Comment by Spandamn** [comment]
Test

**Comment by Spandamn** [comment]
idk why we need this, if there's enough demand, i'll reopen and merge

**Pull request closed without merging**
