### PR TITLE
Do et! pl0x

### PR DESCRIPTION
**Pull request by charizard8888**
<center><h1>Merge it wew I'm tired lel</h1></center>

### CODE REVIEW

**Comment by charizard8888** [comment]
Merge now!

**Comment by charizard8888** [comment]
Trying to get the Pursuit effect
Sprinkle typo error fix
/pminfobox & /trainer card access for Leaders & above
Aliases for Gen 7 Formats
Move Volt Turn Mayhem under Old Other Metas section

**Comment by charizard8888** [comment]
Gonna do formats list next :|

**Comment by charizard8888** [comment]
Fixed it yay!<br>
Also dont merge yet

**Comment by charizard8888** [comment]
<h1>Formats List</h1><h2>Column 1</h2>
<h3>Randomized Metas</h3>
BH BF
Hackmons Cup
Doubles Hackmons Cup

**Comment by Spandamn** [comment]
@charizard8888 
- This PR has shittons of conflicts
- Dont change any format to Gen 7 unless they are a Gen 7 OM and they work for Gen 7

**Comment by charizard8888** [comment]
@Spandamn the conflicts will be resolved as soon as I copy pasta all the stuff you added in ZME + will revert gen 6 metas I think

**Comment by charizard8888** [comment]
Also thanks for fixing ZME :]

**Comment by charizard8888** [comment]
Well fixed the ZME conflicts

**Comment by charizard8888** [comment]
Done all conflicts are resolved now just gotta sort the metas in alphabetical order + according to this https://hastebin.com/raw/ilukuvidum

**Comment by charizard8888** [comment]
Tagging @Spandamn for obvious reasons :]

**Comment by charizard8888** [comment]
Do et tomorrow feelsrs

**Comment by NeverEndingEclipse** [comment]
Who made these

**Comment by charizard8888** [comment]
Wait what

**Comment by Spandamn** [comment]
Merging on your responsibility
Imma revert if this causes crashes

**Comment by charizard8888** [comment]
yay!

**Comment by charizard8888** [comment]
Reverting is ezpz right? hue

**Comment by Spandamn** [comment]
@charizard8888 Conflicts

**Comment by charizard8888** [comment]
No there arent any

**Comment by Spandamn** [comment]
"This branch cannot be rebased due to conflicts
Rebasing the commits of this branch on top of the base branch cannot be performed automatically due to conflicts encountered while reapplying the individual commits from the head branch. "

**Comment by charizard8888** [comment]
I know that ~~just merge and if theres any problem revert~~

**Comment by Spandamn** [comment]
I cant

**Comment by charizard8888** [comment]
hmmface okek

**Comment by Spandamn** [comment]
Fix conflicts, ill instamerge it

**Comment by charizard8888** [comment]
Btw can you tell me where the conflicts are located?

**Comment by Spandamn** [comment]
idk

**Comment by charizard8888** [comment]
hmmface okek I'll see

**Comment by charizard8888** [comment]
Check now idk

**Comment by Spandamn** [comment]
Still conflicts

**Comment by charizard8888** [comment]
Now?

**Comment by Spandamn** [comment]
:(

**Comment by charizard8888** [comment]
Now?

**Comment by Spandamn** [comment]
Try making one more PR with just the format changes

**Comment by charizard8888** [comment]
Yeah
Since ZME is fixed 
Lets close this and work on 
Pokemon: The New Generation (Another Pet Mod) aling with Ludicrousity

**Comment by charizard8888** [comment]
Wew we're good now :]

**Pull request closed without merging**
