### PR TITLE
Announce global promotions on discord

### PR DESCRIPTION
**Pull request by TheMezStrikes**

### CODE REVIEW

**Comment by Spandamn** [comment]
Thing is, sometimes there can be promotions for alts

**Comment by Spandamn** [comment]
@charizard8888 wtf dawg lmao

**Comment by charizard8888** [comment]
Dem too late

**Comment by TheMezStrikes** [comment]
XD

**Comment by TheMezStrikes** [comment]
We're terrible

**Comment by charizard8888** [comment]
So uh what now @Spandamn 
~~Don't remove my merge access ;_;~~

**Comment by TheMezStrikes** [comment]
Note to charizard8888: Never merge my commits without spandan's approval because I'm a dangerous person

**Comment by charizard8888** [comment]
Nah jk nothing would happen he's good

**Pull request merged**
