### PR TITLE
Update formats.js

### PR DESCRIPTION
**Pull request by charizard8888**
Add Fusion Evolution

### CODE REVIEW

**Comment by Spandamn** [comment]
DAMN, this code is REKT. Will have to fix it @charizard8888, I'll edit it a few times then merge it (feel free to do the same)

**Comment by charizard8888** [comment]
Yeah

**Comment by charizard8888** [comment]
Gonna do this now

**Comment by charizard8888** [comment]
@Spandamn just gotta fix abilities.js now

**Comment by charizard8888** [comment]
Wew abilities

**Comment by charizard8888** [comment]
Fixed the formats conflict now :p

**Comment by charizard8888** [comment]
@Spandamn Check abilities.js the rest is fine and merge it!

**Comment by charizard8888** [comment]
Al conflicts fixed @Spandamn check abilities.js and marge or just merge without checking that we can work on that later just merge JUST MERGE!!!

**Comment by charizard8888** [comment]
Create moves.js + commenting some moves which I'll code later (so that I dont have to open the page again and again)

**Comment by charizard8888** [comment]
@Spandamn please check now :(

**Comment by Spandamn** [comment]
Conflicts

**Comment by charizard8888** [comment]
@Spandamn everything is fixed!! !!!!!!!!!!!! MEEEERGE

**Comment by charizard8888** [comment]
:C

**Comment by charizard8888** [comment]
@Spandamn @Spandamn @Spandamn merge it before upd8ing formats.js or we'll have conflicts :/

**Comment by charizard8888** [comment]
Gotta redo this ;-;

**Pull request closed without merging**
