### PR TITLE
Add Winona to DHSSB

### PR DESCRIPTION
**Pull request by charizard8888**
Merge this on a warm sunny day lel (jk don't merge it now)

### CODE REVIEW

**Comment by charizard8888** [comment]
Merge this on a warm sunny day (jk don't merge it yet lel)

**Comment by charizard8888** [comment]
Super Duper Wombo Combo : Dragon type | Status move | Accuracy:_ | PP:5 | Effect : Use Nature Power, Weather Ball, Splash and Belly Drum | Animation: Like Revelation Dance | Priority: 0

Ability and Move left
<h1>Not yet</h1>

**Comment by Spandamn** [comment]
ok

**Comment by charizard8888** [comment]
Move + Ability left
I did some stuff in the move though but lel :p

**Comment by charizard8888** [comment]
<h2>Ability</h2>
Dank Zone : Triggers Trick Room, Grassy Terrain and Sunny Day.
<h2>Move</h2>
Super Duper Wombo Combo : Dragon type | Status move | Accuracy:_ | PP:5 | Effect : Use Nature Power, Weather Ball, Splash and Belly Drum | Animation: Like Revelation Dance | Priority: 0

**Comment by Spandamn** [comment]
Ill add it myself :P

**Comment by charizard8888** [comment]
Ah gr8 :P

**Pull request closed without merging**
