### PR TITLE
Dev Tool for adding Istor mons! hope it works

### PR DESCRIPTION
**Pull request by charizard8888**
Yeah I still don't know  about arrays >_>

### CODE REVIEW

**Comment by charizard8888** [comment]
idk how to and it takes a lot of time in coding every mon so just merge it  :P

**Comment by charizard8888** [comment]
dem you edit it imo

**Comment by charizard8888** [comment]
or tell me how to do that

**Comment by Spandamn** [comment]
I'm at a fest where I have to play CS 1.6 so cant do it atm

**Comment by charizard8888** [comment]
:O cool 
np enjoy I'll do something

**Comment by charizard8888** [comment]
Bump :P

**Pull request merged**
