### PR TITLE
Its Snorlax not Butterfree lel soz

### PR DESCRIPTION
**Pull request by charizard8888**
<h1>MERGE + HOTPATCH NOW!</h1>

### CODE REVIEW

**Comment by Spandamn** [comment]
Tell me when to merge

**Comment by charizard8888** [comment]
Merge now! 
:O

**Comment by charizard8888** [comment]
@Spandamn ^

**Comment by charizard8888** [comment]
@Spandamn  ^ this is I said that the number of commits should not be taken into consideration for calcul8ing the contribution rate

**Comment by Spandamn** [comment]
In a pr, iirc the number of changes in it = the number of commits in the repo

**Comment by charizard8888** [comment]
Oh

**Comment by charizard8888** [comment]
Update: Dont merge yet!

**Comment by charizard8888** [comment]
@Spandamn  Final Update: Merge it

**Comment by charizard8888** [comment]
Thanks! Spandamn! :]

**Pull request merged**
