### PR TITLE
Phrase Updates

### PR DESCRIPTION
**Pull request by Spandamn**
@charizard8888 I will require your help here
Simply move the joinphrases into onStart for that mon

### CODE REVIEW

**Comment by Spandamn** [comment]
https://github.com/XpRienzo/DragonHeaven/tree/DHSSB-Updates Start PRs on this branch btw

**Comment by charizard8888** [comment]
Ho! I'm on it :P

**Comment by Spandamn** [comment]
@charizard8888 nevermind

**Comment by charizard8888** [comment]
lel
btw help me with this #377

**Pull request merged**
