### PR TITLE
Update Jillian

### PR DESCRIPTION
**Pull request by EchoGaia**
Right coming from js.beautifier.org

### CODE REVIEW

**Comment by Spandamn** [comment]
Please select "Indent with Tab Character"

**Comment by Spandamn** [comment]
Also you can modify different files in the same pull request

**Comment by Spandamn** [comment]
You have to make the changes to the BRANCH of that pull request, so for this one, it's https://github.com/EchoGaia/DragonHeaven/tree/patch-29

**Comment by Spandamn** [comment]
@EchoGaia hope this notifies you

**Comment by Spandamn** [comment]
Statuses.js?

**Comment by EchoGaia** [comment]
It's the code for the weather Poisoned Scent, it needs to be apart from the moves.

**Comment by Spandamn** [comment]
Statuses.js is crashing

**Comment by EchoGaia** [comment]
i dunno why but i was sure it was that, ok imma test it on the software.

**Comment by EchoGaia** [comment]
nothing else is crashing except this?

**Comment by Spandamn** [comment]
Idk
But statuses.js is definitely crashing

**Comment by EchoGaia** [comment]
I hope it doesn't come from the code itself, i mean the mechanic of the weather. I hope it's just a syntax problem.

**Comment by EchoGaia** [comment]
Btw @Spandamn try merging now.

**Pull request merged**
