### PR TITLE
Add more mons

### PR DESCRIPTION
**Pull request by charizard8888**
Merge it
Credits to YoshiBlaze (AKA piikiki4) and The Cruelest

### CODE REVIEW

**Comment by charizard8888** [comment]
Merge it @Spandamn

**Comment by Spandamn** [comment]
If anything crashes, blames on you

**Comment by Spandamn** [comment]
Can't hotpatch rn

**Comment by charizard8888** [comment]
Np Nothing crashed yay well atleast not yet

**Pull request merged**
