### PR TITLE
Update pokedex.js

### PR DESCRIPTION
**Pull request by EchoGaia**

### CODE REVIEW

**Comment by EchoGaia** [comment]
try merging @charizard8888

**Comment by Spandamn** [comment]
Tfw I'm trying to concentrate on studies and am getting constant notifications

**Comment by EchoGaia** [comment]
You cannot disable them @Spandamn ?

**Comment by Spandamn** [comment]
I can, but I'd rather put my phone on silent because it's not as many notifs as WhatsApp Snapchat and Instagram
(Which I constantly use while studying)

**Comment by EchoGaia** [comment]
mmm ok

**Comment by charizard8888** [comment]
Oh 
xd

**Pull request merged**
