### PR TITLE
Update abilities.js

### PR DESCRIPTION
**Pull request by Snaquaza**

### CODE REVIEW

**Comment by charizard8888** [comment]
@Spandamn merge this, I'm commenting cuz Snaq doesnt know how to tag in Git Hub ;)

**Comment by Spandamn** [comment]
Snaq, to tag, use @<username>

**Comment by charizard8888** [comment]
Challenges aren't working now! ;/
Uptime: 8 days, 20 hours

**Comment by charizard8888** [comment]
Ah they are now nvm

**Comment by Spandamn** [comment]
Rip, yeah I think I should not have merged

**Comment by charizard8888** [comment]
No not that, Restart it!

**Comment by charizard8888** [comment]
Wat

**Pull request merged**
